apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sampleinstanceclasses.deckhouse.io
  labels:
    heritage: deckhouse
    module: cloud-provider-sample
spec:
  group: deckhouse.io
  preserveUnknownFields: false
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            Parameters of a group of Sample VirtualMachines used by `machine-controller-manager` (the [node-manager](https://deckhouse.io/documentation/v1/modules/040-node-manager/) module).

            The `CloudInstanceClass` resource of the `node-manager` module refers to this resource.
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - numCPUs
                - memory
                - imageName
              properties:
                numCPUs:
                  description: |
                    Count of vCPUs to allocate to Sample VirtualMachines.
                  x-doc-examples: [2]
                  type: integer
                memory:
                  description: |
                    Memory in MiB to allocate to Sample VirtualMachines.
                  x-doc-examples: [8192]
                  type: integer
                rootDiskSizeGb:
                  description: |
                    Root disk size in GiB to use in Sample VirtualMachines.

                    The disk will be automatically resized if its size in the template differs from specified.
                  x-doc-examples: [30]
                  x-doc-default: 30
                  type: integer
                imageName:
                  description: |
                    Name of the OS image to base this VM on.
                  x-doc-examples: ['alt-p10-cloud-x86_64.img']
                  type: string
            status:
              type: object
              properties:
                nodeGroupConsumers:
                  type: array
                  items:
                    type: string
      additionalPrinterColumns:
        - name: "Node Groups"
          type: string
          description: NodeGroups which use this instance class.
          jsonPath: .status.nodeGroupConsumers
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  scope: Cluster
  names:
    plural: sampleinstanceclasses
    singular: sampleinstanceclass
    kind: SampleInstanceClass
    categories:
      - cloudinstanceclasses
