# ##### For specific registryMode
# {{- if $.Values.systemRegistry.registryMode }}
# {{- if not (eq $.Values.systemRegistry.registryMode "Direct")  }}
# #####

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: system-registry-manager
#   namespace: d8-system
#   {{- include "helm_lib_module_labels" (list . (dict "app" "system-registry-manager")) | nindent 2 }}
# spec:
#   type: ClusterIP
#   clusterIP: None
#   ports:
#   - name: http
#     protocol: TCP
#     targetPort: 8097
#     port: 8097
#   selector:
#     app: system-registry-manager
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: embedded-registry
#   namespace: d8-system
#   {{- include "helm_lib_module_labels" (list . (dict "app" "embedded-registry")) | nindent 2 }}
# spec:
#   clusterIP: None
#   selector:
#     component: system-registry
#   ports:
#     - protocol: TCP
#       port: 5001
#       targetPort: 5001


# ##### For specific registryMode
# {{- end }}
# {{- end }}
# #####
