---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus-cpp-main
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus-cpp" "prometheus-cpp" "main")) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-cpp
      prometheus: cpp
