---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cpp-scrape-interval
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "prometheus-cpp")) | nindent 2 }}
data:
  scrapeInterval: {{ .Values.prometheus.scrapeInterval | default "30s" }}
