properties:
  additionalExternalNetworkIDs:
    description: Список Network ID, которые будут считаться `ExternalIP` при перечислении адресов у Node.
  storageClass:
    properties:
      exclude:
        description: |
          Полные имена (или regex-выражения имен) StorageClass, которые не будут созданы в кластере.
      default:
        description: |
          > **УСТАРЕЛ**. Вместо этого параметра используйте [global.defaultClusterStorageClass](../../deckhouse-configure-global.html#parameters-defaultclusterstorageclass).

          Имя StorageClass, который будет использоваться в кластере по умолчанию.

          Если параметр не задан, фактическим StorageClass'ом по умолчанию будет один из следующих:
            * Присутствующий в кластере произвольный StorageClass с default-аннотацией.
            * Лексикографически первый StorageClass из [создаваемых модулем](#storage).
