# type: object
# properties:
#   imagesOverride:
#     description: |
#       Переопределение образов
#     properties:
#       registryManager:
#         description: |
#           Образ registry manager-а
#   enableRegistryManager:
#     description: |
#       Флаг включения registry manager-а
#   cluster:
#     description: |
#       Параметры seaweedfs кластера
#     properties:
#       size:
#         description: |
#           Кол-во нод
#   registryMode:
#     description: |
#       Тип регистри
#   upstreamRegistry:
#     properties:
#       upstreamRegistryHost:
#         description: |
#           Host или upstream регистри
#       upstreamRegistryScheme:
#         description: |
#           Схема upstream регистри
#       upstreamRegistryCa:
#         description: |
#           CA сертификат upstream регистри
#       upstreamRegistryPath:
#         description: |
#           Путь upstream регистри
#       upstreamRegistryUser:
#         description: |
#           Имя пользователя для upstream регистри
#       upstreamRegistryPassword:
#         description: |
#           Пароль для upstream регистри
