x-extend:
  schema: config-values.yaml
type: object
properties:
  internal:
    type: object
    default: {}
    properties:
      webhookCertificate:
        type: object
        x-examples:
        - ca: "testca"
          key: "testkey"
          crt: "testcrt"
        properties:
          ca:
            type: string
          key:
            type: string
          crt:
            type: string
      trustedServiceAccounts:
        type: array
        items:
          type: string
        x-examples:
        - ["test1", "test2"]
