type: object
x-examples:
  - mode: Direct
  - mode: Proxy
    proxy:
      ca: ""
      host: dev-registry.deckhouse.io
      password: "password"
      path: /sys/deckhouse-oss
      scheme: http
      user: "user"
  - mode: Detached
    detached:
      storageMode: S3
properties:
  imagesOverride:
    type: object
    default: {}
    description: |
      Images override
    properties:
      registryManager:
        type: string
        description: |
          Registry manager img full path
        x-example:
          - dev-registry.deckhouse.io/registryManager:latest
  enableRegistryManager:
    type: boolean
    description: |
      Registry manager enable flag
    default: false
  mode:
    type: string
    description: |
      Registry mode
    enum: [Direct, Proxy, Detached]
    x-doc-default: Direct
    default: Direct
  detached:
    type: object
    x-example:
      - storageMode: S3
      - storageMode: Fs
    description: |
      Detached mode properties.
    properties:
      storageMode: &storageMode
        enum: [S3, Fs]
        description: |
          The type of data storage for the system registry module.
        x-example:
          - S3
          - Fs
        x-doc-default: Fs
        default: Fs
  proxy:
    type: object
    x-example:
      - ca: ""
        host: dev-registry.deckhouse.io
        password: "password"
        path: /sys/deckhouse-oss
        scheme: http
        user: "user"
      - ca: "<CA>"
        host: dev-registry.deckhouse.io
        password: "password"
        path: /sys/deckhouse-oss
        scheme: https
        user: "user"
    description: |
      Proxy mode properties.
    properties:
      host:
        type: string
        description: |
          Host of upstream registry
        x-example:
          - dev-registry.deckhouse.io
      scheme:
        type: string
        description: |
          Registry access scheme (http or https).
        x-example:
          - https
          - http
      ca:
        type: string
        description: |
          CA of upstream registry
        default: ""
        x-example:
          - ""
      path:
        type: string
        description: |
          Path of upstream registry
        x-example:
          - sys/deckhouse-oss
      user:
        type: string
        description: |
          User of upstream registry
        x-example:
          - license-token
      password:
        type: string
        description: |
          Password of upstream registry
        x-example:
          - "123456"
      storageMode:
        <<: *storageMode
oneOf:
  - required: [mode]
    properties:
      mode:
        enum: [Direct]
    not:
      required: [proxy, detached]
  - required: [mode]
    properties:
      mode:
        enum: [Proxy]
      proxy: {}
    not:
      required: [detached]
  - required: [mode]
    properties:
      mode:
        enum: [Detached]
      detached: {}
    not:
      required: [proxy]
