{{- $providerClusterConfiguration := .Values.cloudProviderSample.internal.providerClusterConfiguration | required "internal.providerClusterConfiguration is required" }}
{{- define "sample_controller_manager_resources" }}
cpu: 25m
memory: 50Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: capsa-controller-manager
  namespace: d8-cloud-provider-sample
  {{- include "helm_lib_module_labels" (list . (dict "app" "capsa-controller-manager" "workload-resource-policy.deckhouse.io" "master")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: capsa-controller-manager
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "capsa-controller-manager"
      minAllowed:
        {{- include "sample_controller_manager_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 50m
        memory: 50Mi
{{- end }}

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: capsa-controller-manager
  namespace: d8-cloud-provider-sample
  {{- include "helm_lib_module_labels" (list . (dict "app" "capsa-controller-manager")) | nindent 2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: capsa-controller-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsa-controller-manager
  namespace: d8-cloud-provider-sample
  {{- include "helm_lib_module_labels" (list . (dict "app" "capsa-controller-manager")) | nindent 2 }}
spec:
  {{- include "helm_lib_deployment_on_master_strategy_and_replicas_for_ha" . | nindent 2 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: capsa-controller-manager
      cluster.x-k8s.io/provider: infrastructure-sample
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app: capsa-controller-manager
        cluster.x-k8s.io/provider: infrastructure-sample
        control-plane: controller-manager
    spec:
      {{- include "helm_lib_node_selector" (tuple . "master") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "any-node" "uninitialized") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}
      {{- include "helm_lib_priority_class" (tuple . "system-cluster-critical") | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "capsa-controller-manager")) | nindent 6 }}
      serviceAccountName: capsa-controller-manager
      imagePullSecrets:
        - name: deckhouse-registry
      terminationGracePeriodSeconds: 10
      containers:
      - name: capsa-controller-manager
        {{- include "helm_lib_module_container_security_context_read_only_root_filesystem" . | nindent 8 }}
        image: {{ include "helm_lib_module_image" (list . "capsaControllerManager") }}
        imagePullPolicy: IfNotPresent
        args:
          - "--leader-elect"
        env:
          - name: SAMPLE_SERVER
            valueFrom:
              secretKeyRef:
                name: sample-credentials
                key: server
          - name: SAMPLE_USERNAME
            valueFrom:
              secretKeyRef:
                name: sample-credentials
                key: username
          - name: SAMPLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sample-credentials
                key: password
          - name: SAMPLE_INSECURE
            valueFrom:
              secretKeyRef:
                name: sample-credentials
                key: insecure
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            {{- include "helm_lib_module_ephemeral_storage_logs_with_extra" 10 | nindent 12 }}
{{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
            {{- include "sample_controller_manager_resources" . | nindent 12 }}
{{- end }}
