apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modules.deckhouse.io
  labels:
    heritage: deckhouse
    app.kubernetes.io/name: deckhouse
    app.kubernetes.io/part-of: deckhouse
spec:
  group: deckhouse.io
  scope: Cluster
  names:
    plural: modules
    singular: module
    kind: Module
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          description: |
            The module representation.

          properties:
            spec:
              type: object
              properties:
                selectedSource:
                  type: string
                  description: The source from which this module can be downloaded.
            properties:
              type: object
              properties:
                availableSources:
                  type: array
                  description: The module available sources.
                  items:
                    type: string
                weight:
                  type: integer
                  description: The module weight (priority).
                source:
                  type: string
                  description: The source that the module uses.
                stage:
                  type: string
                  description: The current stage of the module lifecycle.
                  enum:
                    - Sandbox
                    - Incubating
                    - Graduated
                    - Deprecated
                description:
                  type: string
                  description: The module description.
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: The module phase.
                message:
                  type: string
                  description: The additional information.
                hooksState:
                  type: string
                  description: "Hooks status report"
      subresources:
        status: {}
